# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('date_pub', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
