# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171214_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shortt',
            new_name='short',
        ),
    ]
